config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  resources :pedidos
  resources :bicos
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pedidos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bico.rb
class Bico < ApplicationRecord
    has_many :pedido
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :pedido
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    belongs_to :bico, optional: true
    belongs_to :cliente, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicos_controller.rb
class BicosController < ApplicationController
  before_action :set_bico, only: [:show, :edit, :update, :destroy]

  # GET /bicos
  # GET /bicos.json
  def index
    @bicos = Bico.all
  end

  # GET /bicos/1
  # GET /bicos/1.json
  def show
  end

  # GET /bicos/new
  def new
    @bico = Bico.new
  end

  # GET /bicos/1/edit
  def edit
  end

  # POST /bicos
  # POST /bicos.json
  def create
    @bico = Bico.new(bico_params)

    respond_to do |format|
      if @bico.save
        format.html { redirect_to @bico, notice: 'Bico was successfully created.' }
        format.json { render :show, status: :created, location: @bico }
      else
        format.html { render :new }
        format.json { render json: @bico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicos/1
  # PATCH/PUT /bicos/1.json
  def update
    respond_to do |format|
      if @bico.update(bico_params)
        format.html { redirect_to @bico, notice: 'Bico was successfully updated.' }
        format.json { render :show, status: :ok, location: @bico }
      else
        format.html { render :edit }
        format.json { render json: @bico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicos/1
  # DELETE /bicos/1.json
  def destroy
    @bico.destroy
    respond_to do |format|
      format.html { redirect_to bicos_url, notice: 'Bico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bico
      @bico = Bico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bico_params
      params.require(:bico).permit(:ipe, :dk_code, :color, :flow_rate, :drilling)
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:first_name, :company, :cnpj, :number, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]
  before_action :set_bico_options, only:[:new,:create,:edit,:update]
  before_action :set_cliente_options, only:[:new,:create,:edit,:update]
  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bico_options
      @bico_options = Bico.all.pluck(:ipe, :id)
    end
    ############
    def set_cliente_options
      @cliente_options = Cliente.all.pluck(:first_name, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:data_matrix, :preco, :data_fab, :data_pedido, :data_entrega, :bico_id, :cliente_id)
    end
end

app/helpers/addbico_pedidos_helper.rb
module AddbicoPedidosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicos_helper.rb
module BicosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/bicos/_form.html.erb
<%= form_with(model: bico, local: true) do |form| %>
  <% if bico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bico.errors.count, "error") %> prohibited this bico from being saved:</h2>

      <ul>
      <% bico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ipe %>
    <%= form.text_field :ipe %>
  </div>

  <div class="field">
    <%= form.label :dk_code %>
    <%= form.text_field :dk_code %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :flow_rate %>
    <%= form.text_field :flow_rate %>
  </div>

  <div class="field">
    <%= form.label :drilling %>
    <%= form.text_field :drilling %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicos/edit.html.erb
<h1>Editing Bico</h1>

<%= render 'form', bico: @bico %>

<%= link_to 'Show', @bico %> |
<%= link_to 'Back', bicos_path %>

app/views/bicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicos</h1>

<table>
  <thead>
    <tr>
      <th>Ipe</th>
      <th>Dk code</th>
      <th>Color</th>
      <th>Flow rate</th>
      <th>Drilling</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicos.each do |bico| %>
      <tr>
        <td><%= bico.ipe %></td>
        <td><%= bico.dk_code %></td>
        <td><%= bico.color %></td>
        <td><%= bico.flow_rate %></td>
        <td><%= bico.drilling %></td>
        <td><%= link_to 'Show', bico %></td>
        <td><%= link_to 'Edit', edit_bico_path(bico) %></td>
        <td><%= link_to 'Destroy', bico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bico', new_bico_path %>

app/views/bicos/new.html.erb
<h1>New Bico</h1>

<%= render 'form', bico: @bico %>

<%= link_to 'Back', bicos_path %>

app/views/bicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ipe:</strong>
  <%= @bico.ipe %>
</p>

<p>
  <strong>Dk code:</strong>
  <%= @bico.dk_code %>
</p>

<p>
  <strong>Color:</strong>
  <%= @bico.color %>
</p>

<p>
  <strong>Flow rate:</strong>
  <%= @bico.flow_rate %>
</p>

<p>
  <strong>Drilling:</strong>
  <%= @bico.drilling %>
</p>

<%= link_to 'Edit', edit_bico_path(@bico) %> |
<%= link_to 'Back', bicos_path %>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Company</th>
      <th>Cnpj</th>
      <th>Number</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.first_name %></td>
        <td><%= cliente.company %></td>
        <td><%= cliente.cnpj %></td>
        <td><%= cliente.number %></td>
        <td><%= cliente.address %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @cliente.first_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @cliente.company %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @cliente.cnpj %>
</p>

<p>
  <strong>Number:</strong>
  <%= @cliente.number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cliente.address %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sagres</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido, local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_matrix %>
    <%= form.text_field :data_matrix %>
  </div>

  <div class="field">
  <%= form.label :ipe %>
  <%= form.select("bico_id", @bico_options, { include_blank: true }) %>
  </div>
  
  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
  <%= form.label :first_name %>
  <%= form.select("cliente_id", @cliente_options, { include_blank: true }) %>
  </div>

  <div class="field">
    <%= form.label :data_fab %>
    <%= form.date_select :data_fab %>
  </div>

  <div class="field">
    <%= form.label :data_pedido %>
    <%= form.date_select :data_pedido %>
  </div>

  <div class="field">
    <%= form.label :data_entrega %>
    <%= form.date_select :data_entrega %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Data matrix</th>
      <th>Ipe</th>
      <th>Preco</th>
      <th>Cliente</th>
      <th>Data fab</th>
      <th>Data pedido</th>
      <th>Data entrega</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.data_matrix %></td>
        <td><%= pedido.bico.ipe%></td>
        <td><%= pedido.preco%></td>
        <td><%= pedido.cliente.first_name%></td>
        <td><%= pedido.data_fab %></td>
        <td><%= pedido.data_pedido %></td>
        <td><%= pedido.data_entrega %></td>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data matrix:</strong>
  <%= @pedido.data_matrix %>
</p>

<p>
  <strong>Ipe:</strong>
  <%= @pedido.bico_id %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @pedido.preco %>
</p>

<p>
  <strong>First_name:</strong>
  <%= @pedido.cliente_id%>
</p>

<p>
  <strong>Data fab:</strong>
  <%= @pedido.data_fab %>
</p>

<p>
  <strong>Data pedido:</strong>
  <%= @pedido.data_pedido %>
</p>

<p>
  <strong>Data entrega:</strong>
  <%= @pedido.data_entrega %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>